### ISSUE TITLE
sqlserver.sql 报错

### ISSUE THREAD

**Issue by askdong** [dymproject/purest-admin#4]
Msg 1785, Level 16, State 0, Line 5429
将 FOREIGN KEY 约束 'FK_PUREST_O_REFERENCE_PUREST_O' 引入表 'PUREST_ORGANIZATION' 可能会导致循环或多重级联路径。请指定 ON DELETE NO ACTION 或 ON UPDATE NO ACTION，或修改其他 FOREIGN KEY 约束。
Msg 1750, Level 16, State 1, Line 5429
无法创建约束或索引。请参阅前面的错误。

**Comment by dymproject** [comment]
更新一下最新的吧。
